name: Deploy Docs

on:
  push:
    branches: [main]
    paths:
      - docs/**
  workflow_dispatch:

env:
  BASE_URL: /${{ github.event.repository.name }}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install MyST
        run: npm install -g mystmd

      - name: Build Main Docs HTML
        run: myst build --html
        working-directory: docs
        env:
          BASE_URL: /${{ github.event.repository.name }}

      - name: Build Story HTML
        run: myst build --html
        working-directory: docs/story
        env:
          BASE_URL: /${{ github.event.repository.name }}/story

      - name: Combine artifacts
        run: |
          mkdir -p docs/_build/html/story
          cp -r docs/story/_build/html/. docs/_build/html/story/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
